baseURL = 'https://abeacongame.com/'
languageCode = 'en-gb'
title = 'A medieval misadventure'
theme = 'ananke'

[params]
  background_color_class = "bg-black"
  body_classes = "avenir bg-near-black white"
  featured_image = "/images/banner.jpg"
  description = "A point-and-click adventure set in a dark medieval fantasy world"
  site_logo = "/images/logo.png"
  footer_title = "A Beacon"
  text_color = "washed-yellow"

  [params.cusdis]
    host = "https://cusdis.com"
    app_id = "70774b48-8a2c-4760-b907-fb687d608527"

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menus.main]]
  name = "Contact"
  url = "/contact/"
  weight = 20
